# Generated by Django 4.1.7 on 2023-03-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'reacher_tb',
            },
        ),
    ]
