# Generated by Django 4.1.7 on 2023-03-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_admin_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher_tb',
        ),
    ]
